### ISSUE TITLE
Makefile assumes default python is Python 2

### ISSUE THREAD

**Issue by ISSOtm** [pkmncoraldev/polishedcoral#1]
My system has `python` bound to Python 3, which yields the following error:
```
python gfx.py 2bpp gfx/items/rival_pokedex.png
Traceback (most recent call last):
  File "gfx.py", line 8, in <module>
    from tools import gfx, lz
  File "/home/issotm/rgbds/polishedcoral/tools/gfx.py", line 69
    tiles = sorted(enumerate(tiles), key= lambda (i, tile): i % width)
                                                 ^
SyntaxError: invalid syntax
```

**Comment by ISSOtm** [comment]
Fixed by 8749ec2492cdcbc1b204f91eef739729d6c3ba3f.
